### ISSUE TITLE
The point cloud can not divide 5

### ISSUE THREAD

**Issue by jinfagang** [barrykui/kitti_object_vis#1]
Which means this code can not be done:

```
def load_velo_scan(velo_filename):
    scan = np.fromfile(velo_filename, dtype=np.float64)
    print(scan)
    print(scan.shape)
    scan = scan.reshape((-1, 5))
    return scan
```

The point are 4x value, can not divide by 5, how did you show it when reshape? this code are just broken

**Comment by barrykui** [comment]
Thank you! Bug fixed. We adopt the code to support 5-vector LiDAR point with the option `--pc_label` in the latest version.
