### ISSUE TITLE
data format error

### ISSUE THREAD

**Issue by ZhenpengChenCode** [barrykui/kitti_object_vis#2]
In file "kitti_util.py", 
Function:
def load_velo_scan(velo_filename, n_vec):
    scan = np.fromfile(velo_filename, dtype=np.float64)
    scan = scan.reshape((-1, n_vec))
    return scan

"np.float64" is wrong, should be "np.float32"

**Comment by barrykui** [comment]
Thank you for finding that bug. 
I change the default datatype to "np.float32", and provide option "--dtype64" to support "np.float64" data.
